spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

#추후 redis추가

# 개발 환경용 로깅 설정
logging:
  level:
    root: ${LOG_LEVEL}
    kr.kro.deom: ${APP_LOG_LEVEL}
    org.springframework.security: ${SECURITY_LOG_LEVEL}
    org.springframework.web: ${WEB_LOG_LEVEL}

# 개발 환경 서버 설정
server:
  port: ${SERVER_PORT}
  error:
    include-stacktrace: always
    include-message: always

# Actuator 추가 설정 (개발 환경에서는 더 많은 정보 노출)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
