name: deom backend test

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Tests

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Create application-test.yml
        run: |
          cat > src/main/resources/application-test.yml << EOL
          spring:
            datasource:
              url: jdbc:postgresql://localhost:5432/test_db
              username: postgres
              password: postgres
            jpa:
              hibernate:
                ddl-auto: create-drop
              properties:
                hibernate:
                  dialect: org.hibernate.dialect.PostgreSQLDialect
          EOL

      - name: Test with Gradle
        run: ./gradlew test
        env:
          SPRING_PROFILES_ACTIVE: test


      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: build/reports/tests/
